#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
KERNEL_BUILD_DIR="${KERNEL_BUILD_DIR:-$PROJECT_DIR/build/kernel}"
PACKAGE_BUILD_DIR="${PACKAGE_BUILD_DIR:-$PROJECT_DIR/build/kernel-packages}"
PACKAGE_OUT_DIR="${PACKAGE_OUT_DIR:-$PROJECT_DIR/build/packages}"
PKGBASE="${KERNEL_ARCH_PKGBASE:-arch-avf-linux-android}"
PKGREL="${KERNEL_ARCH_PKGREL:-1}"
PKGARCH="${KERNEL_ARCH_PKGARCH:-aarch64}"
PACKAGER="${KERNEL_ARCH_PACKAGER:-arch-avf}"
URL="${KERNEL_ARCH_URL:-https://github.com/MoozIiSP/arch-avf}"

require_file() {
    local path="$1"
    [ -f "$path" ] || {
        echo "Missing required file: $path" >&2
        exit 1
    }
}

sanitize_pkgver() {
    printf '%s' "$1" | sed 's/[^A-Za-z0-9_+.]/_/g'
}

dir_size() {
    du -sk "$1" | awk '{print $1 * 1024}'
}

write_pkginfo() {
    local pkgdir="$1"
    local pkgname="$2"
    local pkgdesc="$3"
    local size="$4"
    shift 4
    {
        printf '# Generated by arch-avf kernel/package-arch.sh\n'
        printf 'pkgname = %s\n' "$pkgname"
        printf 'pkgbase = %s\n' "$PKGBASE"
        printf 'pkgver = %s-%s\n' "$PKGVER" "$PKGREL"
        printf 'pkgdesc = %s\n' "$pkgdesc"
        printf 'url = %s\n' "$URL"
        printf 'builddate = %s\n' "$BUILDDATE"
        printf 'packager = %s\n' "$PACKAGER"
        printf 'size = %s\n' "$size"
        printf 'arch = %s\n' "$PKGARCH"
        printf 'license = GPL-2.0-only\n'
        printf '%s\n' "$@"
    } > "$pkgdir/.PKGINFO"
}

write_mtree() {
    local pkgdir="$1"
    (
        cd "$pkgdir"
        bsdtar -cf - --format=mtree \
            --uid 0 --gid 0 --uname root --gname root \
            --options='!all,use-set,type,uid,gid,mode,time,size,sha256,link' \
            --exclude .MTREE \
            --exclude .PKGINFO \
            --exclude .INSTALL \
            . |
            gzip -c > .MTREE
    )
}

make_pkg() {
    local pkgdir="$1"
    local pkgname="$2"
    local outfile="$PACKAGE_OUT_DIR/${pkgname}-${PKGVER}-${PKGREL}-${PKGARCH}.pkg.tar.zst"
    write_mtree "$pkgdir"
    (
        cd "$pkgdir"
        bsdtar --zstd -cf "$outfile" \
            --uid 0 --gid 0 --uname root --gname root \
            .PKGINFO .MTREE ${INSTALL_SCRIPT:+.INSTALL} *
    )
    printf '%s\n' "$outfile"
}

require_file "$KERNEL_BUILD_DIR/vmlinuz"
require_file "$KERNEL_BUILD_DIR/kernel.release"
require_file "$KERNEL_BUILD_DIR/kernel.config"
require_file "$KERNEL_BUILD_DIR/kernel.source"
[ -d "$KERNEL_BUILD_DIR/modules/lib/modules" ] || {
    echo "Missing kernel modules: $KERNEL_BUILD_DIR/modules/lib/modules" >&2
    exit 1
}
command -v bsdtar >/dev/null || {
    echo "Missing bsdtar. Install libarchive-tools." >&2
    exit 1
}
command -v zstd >/dev/null || {
    echo "Missing zstd." >&2
    exit 1
}

# shellcheck disable=SC1090
source "$KERNEL_BUILD_DIR/kernel.source"
KERNEL_RELEASE="$(cat "$KERNEL_BUILD_DIR/kernel.release")"
PKGVER="${KERNEL_ARCH_PKGVER:-$(sanitize_pkgver "${KERNEL_VERSION}_${KERNEL_GIT_REF}")}"
BUILDDATE="${SOURCE_DATE_EPOCH:-$(date +%s)}"

rm -rf "$PACKAGE_BUILD_DIR"
mkdir -p "$PACKAGE_BUILD_DIR" "$PACKAGE_OUT_DIR"

kernel_pkgname="$PKGBASE"
kernel_pkgdir="$PACKAGE_BUILD_DIR/$kernel_pkgname"
modulesdir="$kernel_pkgdir/usr/lib/modules/$KERNEL_RELEASE"
install -d \
    "$kernel_pkgdir/boot" \
    "$kernel_pkgdir/etc/mkinitcpio.d" \
    "$kernel_pkgdir/usr/lib/initcpio" \
    "$kernel_pkgdir/usr/share/$kernel_pkgname" \
    "$modulesdir"
cp "$KERNEL_BUILD_DIR/vmlinuz" "$kernel_pkgdir/boot/Image"
cp "$KERNEL_BUILD_DIR/vmlinuz" "$kernel_pkgdir/boot/vmlinuz-$kernel_pkgname"
cp "$KERNEL_BUILD_DIR/vmlinuz" "$modulesdir/vmlinuz"
if [ -s "$KERNEL_BUILD_DIR/Image.gz" ]; then
    cp "$KERNEL_BUILD_DIR/Image.gz" "$kernel_pkgdir/boot/Image.gz"
fi
cp -a "$KERNEL_BUILD_DIR/modules/lib/modules/." "$kernel_pkgdir/usr/lib/modules/"
cp "$KERNEL_BUILD_DIR/kernel.config" "$kernel_pkgdir/usr/share/$kernel_pkgname/config"
cp "$KERNEL_BUILD_DIR/kernel.source" "$kernel_pkgdir/usr/share/$kernel_pkgname/source"
printf '%s\n' "$KERNEL_RELEASE" > "$kernel_pkgdir/usr/share/$kernel_pkgname/kernel.release"
printf '%s\n' "$kernel_pkgname" > "$modulesdir/pkgbase"
cp "$KERNEL_BUILD_DIR/kernel.config" "$modulesdir/config"
cat > "$kernel_pkgdir/etc/mkinitcpio.d/$kernel_pkgname.preset" <<EOF
# mkinitcpio preset file for the '$kernel_pkgname' package

#ALL_config="/etc/mkinitcpio.conf"
ALL_kver="$KERNEL_RELEASE"

PRESETS=('default' 'fallback')

#default_config="/etc/mkinitcpio.conf"
default_image="/boot/initramfs-$kernel_pkgname.img"
#default_options=""

#fallback_config="/etc/mkinitcpio.conf"
fallback_image="/boot/initramfs-$kernel_pkgname-fallback.img"
fallback_options="-S autodetect"
EOF
printf 'dummy file to trigger mkinitcpio to run\n' > "$kernel_pkgdir/usr/lib/initcpio/$KERNEL_RELEASE"
cat > "$kernel_pkgdir/.INSTALL" <<EOF
post_upgrade() {
  if findmnt --fstab -uno SOURCE /boot >/dev/null 2>&1 && ! mountpoint -q /boot; then
    echo "WARNING: /boot appears to be a separate partition but is not mounted."
  fi
}

post_remove() {
  rm -f boot/initramfs-$kernel_pkgname.img
  rm -f boot/initramfs-$kernel_pkgname-fallback.img
}
EOF
INSTALL_SCRIPT=1
write_pkginfo "$kernel_pkgdir" "$kernel_pkgname" \
    "Android common Linux kernel for Arch AVF" \
    "$(dir_size "$kernel_pkgdir")" \
    "depend = coreutils" \
    "depend = kmod" \
    "depend = mkinitcpio>=0.7" \
    "optdepend = mkinitcpio: initramfs generation" \
    "optdepend = linux-firmware: firmware images needed for some devices" \
    "provides = linux=$PKGVER" \
    "provides = linux-aarch64=$PKGVER" \
    "conflict = linux" \
    "conflict = linux-aarch64"
kernel_pkg="$(make_pkg "$kernel_pkgdir" "$kernel_pkgname")"

firmware_pkgname="$PKGBASE-firmware"
firmware_pkgdir="$PACKAGE_BUILD_DIR/$firmware_pkgname"
install -d "$firmware_pkgdir/usr/lib/firmware" "$firmware_pkgdir/usr/share/$firmware_pkgname"
if [ -d "$KERNEL_BUILD_DIR/firmware/usr/lib/firmware" ]; then
    cp -a "$KERNEL_BUILD_DIR/firmware/usr/lib/firmware/." "$firmware_pkgdir/usr/lib/firmware/"
fi
cp "$KERNEL_BUILD_DIR/kernel.source" "$firmware_pkgdir/usr/share/$firmware_pkgname/source"
cat > "$firmware_pkgdir/usr/share/$firmware_pkgname/README" <<EOF
Firmware files installed from the Android common Linux source tree.

Source: $KERNEL_GIT_REPO
Ref: $KERNEL_GIT_REF
Kernel release: $KERNEL_RELEASE
EOF
INSTALL_SCRIPT=
write_pkginfo "$firmware_pkgdir" "$firmware_pkgname" \
    "Firmware from Android common Linux for Arch AVF" \
    "$(dir_size "$firmware_pkgdir")" \
    "provides = linux-firmware" \
    "conflict = linux-firmware"
firmware_pkg="$(make_pkg "$firmware_pkgdir" "$firmware_pkgname")"

sha256sum "$kernel_pkg" "$firmware_pkg" > "$PACKAGE_OUT_DIR/SHA256SUMS"
ls -lh "$kernel_pkg" "$firmware_pkg" "$PACKAGE_OUT_DIR/SHA256SUMS"
