#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OVERLAY_DIR="${AVF_CONFIG_OVERLAY_DIR:-$SCRIPT_DIR/overlay}"
PACKAGE_BUILD_DIR="${AVF_CONFIG_PACKAGE_BUILD_DIR:-$PROJECT_DIR/build/avf-config-package}"
PACKAGE_OUT_DIR="${AVF_CONFIG_PACKAGE_OUT_DIR:-$PROJECT_DIR/build/avf-packages}"
PKGNAME="${AVF_CONFIG_PKGNAME:-arch-avf-config}"
PKGREL="${AVF_CONFIG_PKGREL:-1}"
PKGARCH="${AVF_CONFIG_PKGARCH:-any}"
PACKAGER="${AVF_CONFIG_PACKAGER:-arch-avf}"
URL="${AVF_CONFIG_URL:-https://github.com/MoozIiSP/arch-avf}"

sanitize_pkgver() {
    printf '%s' "$1" | sed 's/[^A-Za-z0-9_+.]/_/g'
}

default_pkgver() {
    local date_part
    date_part="$(date -u +%Y.%m.%d)"
    if git -C "$PROJECT_DIR" rev-parse --short=12 HEAD >/dev/null 2>&1; then
        printf '%s.r%s\n' "$date_part" "$(git -C "$PROJECT_DIR" rev-parse --short=12 HEAD)"
    else
        printf '%s\n' "$date_part"
    fi
}

dir_size() {
    du -sk "$1" | awk '{print $1 * 1024}'
}

write_mtree() {
    local pkgdir="$1"
    (
        cd "$pkgdir"
        bsdtar -cf - --format=mtree \
            --uid 0 --gid 0 --uname root --gname root \
            --options='!all,use-set,type,uid,gid,mode,time,size,sha256,link' \
            --exclude .MTREE \
            --exclude .PKGINFO \
            --exclude .INSTALL \
            . |
            gzip -c > .MTREE
    )
}

make_pkg() {
    local pkgdir="$1"
    local outfile="$PACKAGE_OUT_DIR/${PKGNAME}-${PKGVER}-${PKGREL}-${PKGARCH}.pkg.tar.zst"
    write_mtree "$pkgdir"
    (
        cd "$pkgdir"
        bsdtar --zstd -cf "$outfile" \
            --uid 0 --gid 0 --uname root --gname root \
            .PKGINFO .MTREE .INSTALL *
    )
    printf '%s\n' "$outfile"
}

[ -d "$OVERLAY_DIR" ] || {
    echo "Missing AVF config overlay directory: $OVERLAY_DIR" >&2
    exit 1
}
command -v bsdtar >/dev/null || {
    echo "Missing bsdtar. Install libarchive-tools." >&2
    exit 1
}
command -v zstd >/dev/null || {
    echo "Missing zstd." >&2
    exit 1
}

PKGVER="${AVF_CONFIG_PKGVER:-$(sanitize_pkgver "$(default_pkgver)")}"
BUILDDATE="${SOURCE_DATE_EPOCH:-$(date +%s)}"

rm -rf "$PACKAGE_BUILD_DIR"
mkdir -p "$PACKAGE_BUILD_DIR/$PKGNAME" "$PACKAGE_OUT_DIR"
pkgdir="$PACKAGE_BUILD_DIR/$PKGNAME"
cp -a "$OVERLAY_DIR/." "$pkgdir/"
chmod 0440 "$pkgdir/etc/sudoers.d/10-avf-droid"
cat > "$pkgdir/.INSTALL" <<'EOF'
post_install() {
  droid_user=droid

  if ! getent group 100 >/dev/null; then
    groupadd -g 100 android
  fi

  primary_group="$(getent group 100 | cut -d: -f1)"
  existing_uid1000="$(getent passwd 1000 | cut -d: -f1 || true)"

  if id -u "$droid_user" >/dev/null 2>&1; then
    usermod -u 1000 -g "$primary_group" -d "/home/$droid_user" -m -s /usr/bin/bash "$droid_user"
  elif [ -n "$existing_uid1000" ]; then
    usermod -l "$droid_user" -d "/home/$droid_user" -m -g "$primary_group" -s /usr/bin/bash "$existing_uid1000"
  else
    useradd -m -u 1000 -g "$primary_group" -s /usr/bin/bash "$droid_user"
  fi

  for group in wheel sudo video render seat; do
    getent group "$group" >/dev/null && usermod -aG "$group" "$droid_user"
  done

  install -d -m 0755 "/home/$droid_user"
  if ! grep -Fq "Android Terminal's Debian shell title behavior." "/home/$droid_user/.bashrc" 2>/dev/null; then
    cat >> "/home/$droid_user/.bashrc" <<'BASHRC'
# Match Android Terminal's Debian shell title behavior.
if [[ $- == *i* ]]; then
    unset PROMPT_COMMAND
    PROMPT_COMMAND='printf "\033]0;%s %s\007" "${USER:-droid}" "${HOSTNAME%%.*}"'
fi
BASHRC
  fi
  chown "$droid_user:$primary_group" "/home/$droid_user/.bashrc" 2>/dev/null || true
  loginctl enable-linger "$droid_user" || true
}

post_upgrade() {
  post_install
}
EOF

{
    printf '# Generated by arch-avf rootfs/package-arch.sh\n'
    printf 'pkgname = %s\n' "$PKGNAME"
    printf 'pkgbase = %s\n' "$PKGNAME"
    printf 'pkgver = %s-%s\n' "$PKGVER" "$PKGREL"
    printf 'pkgdesc = Android AVF guest configuration for Arch Linux ARM\n'
    printf 'url = %s\n' "$URL"
    printf 'builddate = %s\n' "$BUILDDATE"
    printf 'packager = %s\n' "$PACKAGER"
    printf 'size = %s\n' "$(dir_size "$pkgdir")"
    printf 'arch = %s\n' "$PKGARCH"
    printf 'license = GPL-2.0-only\n'
    printf 'depend = systemd\n'
    printf 'depend = mkinitcpio\n'
    printf 'depend = sudo\n'
    printf 'optdepend = ttyd: browser terminal service\n'
    printf 'optdepend = avahi: mDNS advertisement for ttyd\n'
} > "$pkgdir/.PKGINFO"

pkg="$(make_pkg "$pkgdir")"
sha256sum "$pkg" > "$PACKAGE_OUT_DIR/SHA256SUMS"
ls -lh "$pkg" "$PACKAGE_OUT_DIR/SHA256SUMS"
